name: Mac_Build
  
on:
  watch:
    types: started

jobs:
  Mac_Build:
    name: Mac_Build
    if: github.event.repository.owner.id == github.event.sender.id
    runs-on: macos-latest
    steps:
      - 
        name: Private Actions Checkout
        uses: actions/checkout@v2.3.4
        with:
          persist-credentials: false
          fetch-depth: 0
      -
        name: IniT Path
        run: |
          # jdk17
          wget https://download.oracle.com/java/17/latest/jdk-17_macos-x64_bin.tar.gz
          # packr
          wget -O packr.jar `curl -u ${{ secrets.DOCKERHUB_USERNAME }}:${{ secrets.TOKEN_GITHUB }} -s https://api.github.com/repos/libgdx/packr/releases/latest | grep "browser_download_url" | cut -d '"' -f 4`
          # Godzilla
          wget `curl -u ${{ secrets.DOCKERHUB_USERNAME }}:${{ secrets.TOKEN_GITHUB }} -s https://api.github.com/repos/BeichenDream/Godzilla/releases/latest | grep "browser_download_url" | cut -d '"' -f 4`
          # Behinder
          wget -O Behinder.zip `curl -u ${{ secrets.DOCKERHUB_USERNAME }}:${{ secrets.TOKEN_GITHUB }} -s https://api.github.com/repos/rebeyond/Behinder/releases/latest | grep "browser_download_url" | cut -d '"' -f 4`
          # openjfx
          wget -O openjfx-16.zip https://download2.gluonhq.com/openjfx/16/openjfx-16_osx-x64_bin-sdk.zip
          ditto -V -x -k   --sequesterRsrc --rsrc Behinder.zip /tmp/Behinder
          unzip openjfx-16.zip
          mkdir Behinder App
          mv /tmp/Behinder/Behinder.jar /tmp/Behinder/server /tmp/Behinder/data.db javafx-sdk-16/lib Behinder  
      - 
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'
      - 
        name: Generate APP
        run: |
          # Godzilla
          java -jar packr.jar Godzilla.json
          # Behinder
          jpackage --name Behinder --input ./Behinder \
            --main-jar Behinder.jar \
            --type dmg  \
            --copyright "Behinder_v3.0 Beta 11【t00ls专版】.XRSec"  \
            --app-version "3.0" \
            --description "Behinder_v3.0 Beta 11【t00ls专版】" \
            --vendor "rebeyond" \
            --mac-package-name "Behinder" \
            --icon Behinder.icns \
            --java-options "-Dfile.encoding=utf-8 -XX:ParallelGCThreads=4  -XX:+AggressiveHeap -XX:+UseParallelGC --module-path \$APPDIR/lib --add-modules=javafx.controls --add-modules=javafx.fxml --add-modules=javafx.base --add-modules=javafx.graphics --add-modules=javafx.web"
          # CobaltStrike
          # jpackage --name CobaltStrike --input ./CobaltStrike \
          #   --main-jar cobaltstrike.jar \
          #   --type dmg  \
          #   --copyright "CobaltStrike_v4.4 .XRSec"  \
          #   --app-version "4.4" \
          #   --description "CobaltStrike_v4.4 .XRSec" \
          #   --mac-package-name "CobaltStrike" \
          #   --icon cobaltstrike.icns \
          #   --java-options "-Dfile.encoding=utf-8 -XX:ParallelGCThreads=4  -XX:+AggressiveHeap -XX:+UseParallelGC -javaagent:\$APPDIR/hook.jar -javaagent:\$APPDIR/cobaltstrikecn.jar"
          zip -r Godzilla.zip Godzilla.app
          mv Godzilla.zip Behinder*.dmg App
#       -
#         name: Generate DMG
#         uses: actions/setup-node@v2
#         with:
#           node-version: '16'
#       - run: |
#           npm install --global create-dmg
#           create-dmg Godzilla.app
#       - name: upload artifacts
#         uses: actions/upload-artifact@v2
#         with:
#           name: mac
#           path: App
      - uses: dev-drprasad/delete-older-releases@v0.2.0
        with:
          repo: XRSec/Three-Musketeers # defaults to current repo
          keep_latest: 3
          delete_tag_pattern: "" # defaults to ""
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
      - name: Get version
        id: time_now
        run: echo "::set-output name=dir::$(date +%Y_%m_%d)"
      - 
        name: release
        uses: softprops/action-gh-release@v1
#         if: startsWith(github.ref, 'refs/tags/')
        with:
          files: "App/**"
          tag_name: ${{ steps.time_now.outputs.dir }}
          release_name: ${{ steps.time_now.outputs.dir }}
          draft: false
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
